[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Hengmeng Zhuang <hezhuang@ucsd.edu>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
]
